// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYM4sz0GneipO8W5nhFanLcClPJ3Z7Iw',
    appId: '1:810131365389:web:4375594d27c15df7e77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    authDomain: 'cloud-message-test-1d41b.firebaseapp.com',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    measurementId: 'G-QYE5VQHZRM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQbNt3HAIWA6e9hZb4DHDjpZqHix4YIA',
    appId: '1:810131365389:ios:9f129d1c6ee8d9fde77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    iosBundleId: 'com.example.testPushNotiFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQbNt3HAIWA6e9hZb4DHDjpZqHix4YIA',
    appId: '1:810131365389:ios:9f129d1c6ee8d9fde77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    iosBundleId: 'com.example.testPushNotiFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDYM4sz0GneipO8W5nhFanLcClPJ3Z7Iw',
    appId: '1:810131365389:web:4f5de5b75462dfdce77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    authDomain: 'cloud-message-test-1d41b.firebaseapp.com',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
    measurementId: 'G-L0Q4L2P39J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXjpUAtFNe7h1Ed92ZPUP50SNchyXLEeQ',
    appId: '1:810131365389:android:2cb204926734553de77f44',
    messagingSenderId: '810131365389',
    projectId: 'cloud-message-test-1d41b',
    storageBucket: 'cloud-message-test-1d41b.appspot.com',
  );

}